name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Valgrind
      run: sudo apt-get install valgrind

    - name: Configure
      run: mkdir build && cd build && cmake ..

    - name: Build
      run: cd build && make
      
    - name: Test
      run: cd build && make test
